version: 2
jobs:
  build:
    working_directory: ~/rx-sandbox
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - run:
          name: Checking Versions
          command: |
            npm install -g yarn
            # prevent npm upgrade failure in docker
            yarn global add npm@5.6.0
            npm install -g greenkeeper-lockfile@1
            node --version && npm --version
      - run:
          name: prepare
          command: npm install
      - run:
          name: lockfile update
          command: greenkeeper-lockfile-update
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: |
            npm test
            bash <(curl -s https://codecov.io/bash)
      - run:
          name: lockfile upload
          command: greenkeeper-lockfile-upload