name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '12', '13', '14', '15', '16' ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    name: ${{ matrix.os }} / Node ${{ matrix.node }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install
      run: |
        npm install -g npm@latest
        npm ci
    - name: lint
      run: npm run lint
    - name: build
      run: npm run build
    - name: test
      run: npm test
